// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/protos/domain.proto

package grpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Log struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	Level                int64    `protobuf:"varint,2,opt,name=Level,proto3" json:"Level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Log) Reset()         { *m = Log{} }
func (m *Log) String() string { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()    {}
func (*Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ed6485d0e68e385, []int{0}
}

func (m *Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Log.Unmarshal(m, b)
}
func (m *Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Log.Marshal(b, m, deterministic)
}
func (m *Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Log.Merge(m, src)
}
func (m *Log) XXX_Size() int {
	return xxx_messageInfo_Log.Size(m)
}
func (m *Log) XXX_DiscardUnknown() {
	xxx_messageInfo_Log.DiscardUnknown(m)
}

var xxx_messageInfo_Log proto.InternalMessageInfo

func (m *Log) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Log) GetLevel() int64 {
	if m != nil {
		return m.Level
	}
	return 0
}

type Power struct {
	Power                bool     `protobuf:"varint,1,opt,name=power,proto3" json:"power,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Power) Reset()         { *m = Power{} }
func (m *Power) String() string { return proto.CompactTextString(m) }
func (*Power) ProtoMessage()    {}
func (*Power) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ed6485d0e68e385, []int{1}
}

func (m *Power) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Power.Unmarshal(m, b)
}
func (m *Power) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Power.Marshal(b, m, deterministic)
}
func (m *Power) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Power.Merge(m, src)
}
func (m *Power) XXX_Size() int {
	return xxx_messageInfo_Power.Size(m)
}
func (m *Power) XXX_DiscardUnknown() {
	xxx_messageInfo_Power.DiscardUnknown(m)
}

var xxx_messageInfo_Power proto.InternalMessageInfo

func (m *Power) GetPower() bool {
	if m != nil {
		return m.Power
	}
	return false
}

type Move struct {
	Speed                int64    `protobuf:"varint,1,opt,name=speed,proto3" json:"speed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Move) Reset()         { *m = Move{} }
func (m *Move) String() string { return proto.CompactTextString(m) }
func (*Move) ProtoMessage()    {}
func (*Move) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ed6485d0e68e385, []int{2}
}

func (m *Move) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Move.Unmarshal(m, b)
}
func (m *Move) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Move.Marshal(b, m, deterministic)
}
func (m *Move) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Move.Merge(m, src)
}
func (m *Move) XXX_Size() int {
	return xxx_messageInfo_Move.Size(m)
}
func (m *Move) XXX_DiscardUnknown() {
	xxx_messageInfo_Move.DiscardUnknown(m)
}

var xxx_messageInfo_Move proto.InternalMessageInfo

func (m *Move) GetSpeed() int64 {
	if m != nil {
		return m.Speed
	}
	return 0
}

type Brake struct {
	Radius               int64    `protobuf:"varint,1,opt,name=radius,proto3" json:"radius,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Brake) Reset()         { *m = Brake{} }
func (m *Brake) String() string { return proto.CompactTextString(m) }
func (*Brake) ProtoMessage()    {}
func (*Brake) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ed6485d0e68e385, []int{3}
}

func (m *Brake) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Brake.Unmarshal(m, b)
}
func (m *Brake) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Brake.Marshal(b, m, deterministic)
}
func (m *Brake) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Brake.Merge(m, src)
}
func (m *Brake) XXX_Size() int {
	return xxx_messageInfo_Brake.Size(m)
}
func (m *Brake) XXX_DiscardUnknown() {
	xxx_messageInfo_Brake.DiscardUnknown(m)
}

var xxx_messageInfo_Brake proto.InternalMessageInfo

func (m *Brake) GetRadius() int64 {
	if m != nil {
		return m.Radius
	}
	return 0
}

type Emergency struct {
	Emergency            bool     `protobuf:"varint,1,opt,name=emergency,proto3" json:"emergency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Emergency) Reset()         { *m = Emergency{} }
func (m *Emergency) String() string { return proto.CompactTextString(m) }
func (*Emergency) ProtoMessage()    {}
func (*Emergency) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ed6485d0e68e385, []int{4}
}

func (m *Emergency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Emergency.Unmarshal(m, b)
}
func (m *Emergency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Emergency.Marshal(b, m, deterministic)
}
func (m *Emergency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Emergency.Merge(m, src)
}
func (m *Emergency) XXX_Size() int {
	return xxx_messageInfo_Emergency.Size(m)
}
func (m *Emergency) XXX_DiscardUnknown() {
	xxx_messageInfo_Emergency.DiscardUnknown(m)
}

var xxx_messageInfo_Emergency proto.InternalMessageInfo

func (m *Emergency) GetEmergency() bool {
	if m != nil {
		return m.Emergency
	}
	return false
}

type Error struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ed6485d0e68e385, []int{5}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Log)(nil), "domain.Log")
	proto.RegisterType((*Power)(nil), "domain.Power")
	proto.RegisterType((*Move)(nil), "domain.Move")
	proto.RegisterType((*Brake)(nil), "domain.Brake")
	proto.RegisterType((*Emergency)(nil), "domain.Emergency")
	proto.RegisterType((*Error)(nil), "domain.Error")
}

func init() { proto.RegisterFile("internal/protos/domain.proto", fileDescriptor_4ed6485d0e68e385) }

var fileDescriptor_4ed6485d0e68e385 = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0xd0, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0x07, 0x70, 0xba, 0xae, 0xd5, 0x3e, 0x10, 0x21, 0x88, 0xf4, 0x50, 0x71, 0xe4, 0x34, 0x2f,
	0xee, 0x20, 0xfb, 0x02, 0x83, 0xdd, 0x36, 0x90, 0x1c, 0xbd, 0xc5, 0xe6, 0x11, 0x8a, 0x6b, 0x5e,
	0x78, 0x99, 0x13, 0xbf, 0xbd, 0x34, 0x49, 0xdd, 0xed, 0xfd, 0xfa, 0xe7, 0xd1, 0xfc, 0x1f, 0x74,
	0x83, 0x3b, 0x23, 0x3b, 0x7d, 0xda, 0x78, 0xa6, 0x33, 0x85, 0x8d, 0xa1, 0x51, 0x0f, 0xee, 0x35,
	0x4a, 0xd4, 0x49, 0x72, 0x0b, 0xe5, 0x81, 0xac, 0x68, 0xe1, 0xe6, 0x88, 0x21, 0x68, 0x8b, 0x6d,
	0xb1, 0x2a, 0xd6, 0x8d, 0x9a, 0x29, 0x1e, 0xa0, 0x3a, 0xe0, 0x05, 0x4f, 0xed, 0x62, 0x55, 0xac,
	0x4b, 0x95, 0x20, 0x9f, 0xa0, 0x7a, 0xa7, 0x1f, 0xe4, 0x29, 0xf6, 0xd3, 0x10, 0xd7, 0x6e, 0x55,
	0x82, 0xec, 0x60, 0x79, 0xa4, 0x4b, 0x5c, 0x0e, 0x1e, 0xd1, 0xc4, 0xb4, 0x54, 0x09, 0xf2, 0x19,
	0xaa, 0x1d, 0xeb, 0x2f, 0x14, 0x8f, 0x50, 0xb3, 0x36, 0xc3, 0x77, 0xc8, 0x79, 0x96, 0x7c, 0x81,
	0x66, 0x3f, 0x22, 0x5b, 0x74, 0xfd, 0xaf, 0xe8, 0xa0, 0xc1, 0x19, 0xf9, 0x2f, 0xd7, 0x0f, 0x72,
	0x0b, 0xd5, 0x9e, 0x99, 0x58, 0x08, 0x58, 0xf6, 0x64, 0xe6, 0xe7, 0xc7, 0x79, 0x6a, 0x35, 0xe6,
	0x56, 0x8b, 0xd4, 0x2a, 0x73, 0x77, 0xff, 0x71, 0xf7, 0x7f, 0x1e, 0xcb, 0xbe, 0xff, 0xac, 0xe3,
	0x59, 0xde, 0xfe, 0x02, 0x00, 0x00, 0xff, 0xff, 0xbf, 0x22, 0x4f, 0xce, 0x36, 0x01, 0x00, 0x00,
}
